apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: notdefault
  namespace: metallb-system
spec:
  addresses:
  - 172.19.254.16/28
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: notdefault
  namespace: metallb-system
spec:
  ipAddressPools:
  - notdefault