kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onos-config
  namespace: micro-onos-data
subjects:
- kind: ServiceAccount
  name: onos-config
  namespace: micro-onos-${CLUSTER1}
- kind: ServiceAccount
  name: onos-config
  namespace: micro-onos-${CLUSTER2}
roleRef:
  kind: Role
  name: onos-config
  apiGroup: rbac.authorization.k8s.io
