apiVersion: atomix.io/v3beta4
kind: StorageProfile
metadata:
  name: onos-topo
  namespace: micro-onos-${CLUSTER1}
  labels:
    name: onos-topo
    chart: "onos-topo-1.5.1"
    release: "onos-umbrella"
    heritage: "Helm"
spec:
  routes:
  - store:
      name: onos-raft-data-topo
      namespace: micro-onos-data
    rules:
    - names:
      - '*'
    - apiVersion: v1
      config:
        cache:
          enabled: true
      kind: Map
  # - store:
  #     name: onos-raft-data-topo
  #     namespace: micro-onos-data-2
  #   rules:
  #   - names:
  #     - '*'
  #   - apiVersion: v1
  #     config:
  #       cache:
  #         enabled: true
  #     kind: Map
